blog/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name = 'index'),

    #设置url
    url(r'^article/(?P<article_id>\d+)$',\
        views.ArticleDetailView.as_view(), name = 'detail'),
    ]

filesystem/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from filesystem import views

urlpatterns = [
##    url(r'^$', views.IndexView.as_view(), name = 'index'),
##
##    #设置url
##    url(r'^article/(?P<article_id>\d+)$',\
##        views.ArticleDetailView.as_view(), name = 'detail'),
	url(r'^$', views.list, name = 'list')
    ]

mysite/urls.py
# -*- coding:utf-8 -*-

"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin
from blog import views
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace = 'blog', app_name = 'blog')),
    url(r'^file/', include('filesystem.urls', \
                           namespace = 'file', app_name = 'file')),
    #设置默认主页
    url(r'^$', RedirectView.as_view(url='/file', permanent=True)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding:utf-8 -*-
from django.db import models


class Article(models.Model):
    #设置status
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
    )

    title = models.CharField('标题', max_length=70)
    body = models.TextField('正文')
    created_time = models.DateTimeField('创建时间', auto_now_add=True)
    last_modified_time = models.DateTimeField('修改时间', auto_now=True)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES)
    abstract = models.CharField('摘要', max_length=54, blank=True, null=True, help_text="可选，如若为空将摘取正文的前54个字符")
    #views和like不显示
    views = models.PositiveIntegerField('浏览量', default=0)
    likes = models.PositiveIntegerField('点赞数', default=0)
    topped = models.BooleanField('置顶', default=False)

    
    #保存body到摘要里面
    def save(self, *args, **kwargs):
        self.abstract = self.abstract or self.body[:54]
        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return self.title.encode("utf-8")

    class Meta:
        #默认排序方式
        ordering = ['-last_modified_time']

filesystem/models.py
from django.db import models
from django import forms
import os, wmi
# Create your models here.


class Document(models.Model):
        docfile = models.FileField(upload_to = 'documents/%Y/%m/%d')

        def get_fs_info():
                tmplist = []
                c = wmi.WMI()
                for physical_disk in c.Win32_DiskDrive():
                        for partition in physical_disk.associators("Win32_DiskDriveToDiskPartition"):
                                for logical_disk in partition.associators("Win32_LogicalDiskToPartition"):
                                        if logical_disk.Caption == os.path.splitdrive(os.getcwd())[0]:
                                                FreeSpace=int(logical_disk.FreeSpace)/1024/1024/1024  
                return FreeSpace

	
class DocumentForm(forms.Form):
	docfile = forms.FileField(label = 'Select a file')

blog/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Article
import markdown2



class IndexView(ListView):
    #联系html
    template_name = "blog/index.html"

    def get_queryset(self):
        article_list = Article.objects.filter(status = 'p')
        for article in article_list:
            article.body = markdown2.markdown(article.body)
            article.abstract = markdown2.markdown(article.abstract)
        return article_list


class ArticleDetailView(DetailView):
    #继承Article类
    model = Article
    template_name = "blog/detail.html"
    #设置pk的数据
    pk_url_kwarg = 'article_id'

    def get_object(self):
        # 实例化get_object()
        article = super(ArticleDetailView, self).get_object()
	article.views += 1
	article.save()
        article.body = markdown2.markdown(article.body)
        return article

filesystem/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic.list import ListView
from .models import Document, DocumentForm
import wmi, os


def list(request):
    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(docfile=request.FILES['docfile'])
            newdoc.save()

            # Redirect to the document list after POST
            return HttpResponseRedirect(reverse('file:list'))
    else:
        form = DocumentForm()  # A empty, unbound form

    # Load documents for the list page
    documents = Document.objects.all()

    # Render list page with the documents and the form
    return render_to_response(
        'list.html',
        {'documents': documents, 'form': form},
        context_instance=RequestContext(request)
    )

##class ListView(ListView):
##    templates_name = "list.html"
##    if request.method == 'POST':
##        form = DocumentForm(request.POST, request.FILES)
##        if form.is_valid():
##            newdoc = Document(docfile=request.FILES['docfile'])
##            newdoc.save()
##
##            # Redirect to the document list after POST
##            return HttpResponseRedirect(reverse('file:list'))
##    else:
##        form = DocumentForm()  # A empty, unbound form
##
##    # Load documents for the list page
##    documents = Document.objects.all()
    
    

blog/templates/base.html
<DOCTYPE html>

<html>
<head>
	<meta charset = "UTF -8">
	<title>blog</title>
</head>


<body style="margin:0;padding:0;">

{% block content %} {% endblock %}

</body>
</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% block content %}

{% load staticfiles %}

<h1><a href = "{% url 'blog:index' %}" style='text-decoration:none;color: #2d6dcc'>Blog</a></h1>


<table border=0 height=600px align=left>
	<tr>
		<td width=20% align=left valign=top style="BORDER-RIGHT: #999999 1px dashed">
			<ul id="tree" class="ztree">
			</ul>
		</td>
		
		<td width=80% align=left valign=top >
			<p align = left> 创建时间：{{article.created_time|date:"Y年n月d日"}}</p>
			{{ article.body |safe }}
		</td>
	</tr>
</table>


 <link rel="stylesheet" href="{% static 'blog/css/zTreeStyle/zTreeStyle.css' %}">
  <style>
	body {
	background-color: white;
	margin:0; padding:0;
	text-align: center;
	}
	div, p, table, th, td {
		list-style:none;
		margin:0; padding:0;
		color:#333; font-size:16px;
		font-family:dotum, Verdana, Arial, Helvetica, AppleGothic, sans-serif;
	}
	.ztree li a.curSelectedNode {
		padding-top: 0px;
		background-color: #FFE6B0;
		color: black;
		height: 16px;
		border: 1px #FFB951 solid;
		opacity: 0.8;
	}
  </style>
<script type="text/javascript" src="{% static 'blog/js/jquery-1.4.4.min.js' %}" type="text/css"></script>
<script type="text/javascript" src="{% static 'blog/js/jquery.ztree.core-3.5.js' %}"></script>
<script type="text/javascript" src="{% static 'blog/src/ztree_toc.js' %}"></script>
	<SCRIPT type="text/javascript" >
	<!--
	$(document).ready(function(){
		$('#tree').ztree_toc({

		});
	});
	//-->
	</SCRIPT>




{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block content %}


{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/css/mybtn14_3/mybtn14_3.css' %}">


<div class="mybtn14_3" style="text-align:center;background:#2d6dcc; color:#FFF;margin:0;">
<span style="float:right;">
<a href = "{% url 'admin:index' %}" style='text-decoration:none;'>登录</a>
<a href = "{% url 'file:list' %}" style='text-decoration:none;'>上传</a>
</span>

<span style="float:center;">
<h1><a href = "{% url 'blog:index' %}" style='text-decoration:none;'>Blog</a></h1>
</span>
</div>

<hr/>

<div style = "width:70%;border-left: 0px solid #000;border-right: 0px solid #000;position: absolute;background-color:#FFF;left:15%">	
	{% for article in article_list %}
		<p><a href = "{% url 'blog:detail' article.pk %}">
		{{article.title}}
		</a></p>
		摘要：{{article.abstract|safe}}
		<p align = right>{{article.last_modified_time|date:"Y年n月d日"}}</p>
		<p align = right>浏览量：{{article.views}}</p>
		<hr/>
	{% endfor %}
</div>


{% endblock %}

filesystem/templates/base.html
<DOCTYPE html>

<html>
<head>
	<meta charset = "UTF -8">
	<title>blog</title>
</head>


<body style="margin:0;padding:0;">

{% block content %} {% endblock %}

</body>
</html>

filesystem/templates/list.html
{% extends 'base.html' %}
{% block content %}


{% load staticfiles %}
<link rel="stylesheet" href="{% static 'blog/css/mybtn14_3/mybtn14_3.css' %}">


<div class="mybtn14_3" style="text-align:center;background:#2d6dcc; color:#FFF;margin:0;">
<span style="float:right;">
<a href = "{% url 'admin:index' %}" style='text-decoration:none;'>登录</a>
</span>

<span style="float:center;">
<h1><a href = "{% url 'blog:index' %}" style='text-decoration:none;'>Blog</a></h1>
</span>
</div>

<hr/>
        <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'file:list' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>

            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>

            <p>
                {{ form.docfile.errors }}
                {{ form.docfile }}
            </p>

            <p><input type="submit" value="Upload"/></p>
        </form>
		
		<br/><hr/>
		


		<!-- List of uploaded documents -->
		<p>文件列表：</p>
        {% if documents %}
            <ul>
                {% for document in documents %}
                    <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No documents.</p>
        {% endif %}


{% endblock %}